### ISSUE TITLE
Empty directories are listed in navbar

### ISSUE THREAD

**Issue by mistic100** [mysiki/mkdocs_include_dir_to_nav#3]
Given the following configuration:

```yaml
nav:
  - Home: index.md
  - Wiki: wiki
```

And directory structure :

```
docs/
├── index.md
├── wiki
│   ├── page01.md
│   ├── page02.md
│   ├── .git
│   │   └── standard content of a git directory
│   └── uploads
│       └── image.jpg
```

The Wiki section contains page01 and page02 as expected but also the directories from '.git' and 'upload' which are of course empty.

And mkdocs yields a bunch of wanring :

```
WARNING  -  A relative path to 'wiki/.git/branches' is included in the 'nav' configuration, which is not found in the documentation files
WARNING  -  A relative path to 'wiki/.git/hooks' is included in the 'nav' configuration, which is not found in the documentation files
..............
WARNING  -  A relative path to 'wiki/uploads/0338348467190a8454583aff401769d8' is included in the 'nav' configuration, which is not found in the documentation files
..............
```

Motivation : I am adding the content of the Gitlab Wiki repository while building the documentation

Directories not containing any file matching 'file_pattern' should be ignored

**Comment by mysiki** [comment]
seems legit, I will check it asap.

**Comment by mysiki** [comment]
asap take a while ... But it's done : https://github.com/mysiki/mkdocs_include_dir_to_nav/releases/tag/v1.2.0

Tested ok, reopen if needed

**Comment by mistic100** [comment]
Thank you
